---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-cookstyle-runner-chef-cookbooks
spec:
  schedule: "0 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: github-cookstyle-runner
              image: xorima/github-cookstyle-runner:1.3.3
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: xorimabot-github
                      key: github_token
                - name: GCR_DESTINATION_REPO_OWNER
                  value: chef-cookbooks
                - name: GCR_DESTINATION_REPO_TOPICS
                  value: "cookbook"
                - name: GCR_BRANCH_NAME
                  value: "automated/cookstyle"
                - name: GCR_PULL_REQUEST_TITLE
                  value: "Automated PR: Cookstyle Changes"
                - name: GCR_GIT_NAME
                  value: "Xorima Bot"
                - name: GCR_GIT_EMAIL
                  value: "xorimabot@avon-lea.co.uk"
                - name: GCR_GIT_USERNAME
                  value: "xorimabot"
                - name: GCR_CHANGELOG_LOCATION
                  value: "CHANGELOG.md"
                - name: GCR_CHANGELOG_MARKER
                  value: "## Unreleased"
                - name: GCR_MANAGE_CHANGELOG
                  value: "1"
          restartPolicy: Never
